// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

/* Normally generated by the OBS build. The plugin only needs the release
 * flags; resource paths come from obs_module_file at runtime. */
#define OBS_RELEASE_CANDIDATE 0
#define OBS_BETA 0
